### ISSUE TITLE
"There is no thread support in this instance.    [Condition of type BORDEAUX-THREADS::BORDEAUX-MP-CONDITION]"

### ISSUE THREAD

**Issue by zepadovani** [byulparan/cl-collider#1]
Hi!

I've just installed everything and I'm trying to boot the server, but I get this error:
There is no thread support in this instance.
   [Condition of type BORDEAUX-THREADS::BORDEAUX-MP-CONDITION]

Restarts:
 0: [RETRY] Retry SLIME interactive evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 8: #<CLOSURE (LABELS SWANK/SBCL::RUN :IN SWANK/BACKEND:ADD-FD-HANDLER) {15C3490D}>>
 3: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: (BORDEAUX-THREADS::%MAKE-THREAD #<unavailable argument> #<unavailable argument>)
  1: (SCHEDULER:SCHED-RUN #<SCHEDULER:SCHEDULER {1404B051}>)
  2: ((:METHOD SERVER-BOOT (RT-SERVER)) #<SC-SYNTH localhost-127.0.0.1:57999>) [fast-method]
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SERVER-BOOT _S_) #<NULL-LEXENV>)
  4: (EVAL (SERVER-BOOT _S_))
There is no thread support in this instance.
   [Condition of type BORDEAUX-THREADS::BORDEAUX-MP-CONDITION]

Restarts:
 0: [RETRY] Retry SLIME interactive evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [REMOVE-FD-HANDLER] Remove #<SB-IMPL::HANDLER INPUT on descriptor 8: #<CLOSURE (LABELS SWANK/SBCL::RUN :IN SWANK/BACKEND:ADD-FD-HANDLER) {15C3490D}>>
 3: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: (BORDEAUX-THREADS::%MAKE-THREAD #<unavailable argument> #<unavailable argument>)
  1: (SCHEDULER:SCHED-RUN #<SCHEDULER:SCHEDULER {1404B051}>)
  2: ((:METHOD SERVER-BOOT (RT-SERVER)) #<SC-SYNTH localhost-127.0.0.1:57999>) [fast-method]
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SERVER-BOOT _S_) #<NULL-LEXENV>)
  4: (EVAL (SERVER-BOOT _S_))
  5: (SWANK::EVAL-REGION "(server-boot _s_)")
      Locals:
        SB-DEBUG::ARG-0 = "(server-boot _s_)"
  6: ((LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL-REGION))
  7: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME interactive evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL-REGION) {149A227D}>)
  8: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL-REGION) {149A226D}>)
  9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK:INTERACTIVE-EVAL-REGION "(server-boot _s_)") #<NULL-LEXENV>)
 10: (EVAL (SWANK:INTERACTIVE-EVAL-REGION "(server-boot _s_)"))
 11: (SWANK:EVAL-FOR-EMACS (SWANK:INTERACTIVE-EVAL-REGION "(server-boot _s_)") ":sc" 12)
 12: (SWANK::PROCESS-REQUESTS T)
 13: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 14: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
 15: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1499FDB5}>)
 16: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/Users/ze/slime/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1499FDB5}>)
 17: (SWANK::HANDLE-REQUESTS #<SWANK::SINGLETHREADED-CONNECTION {15C34881}> T)
 18: ((LABELS SWANK/SBCL::RUN :IN SWANK/BACKEND:ADD-FD-HANDLER) 8)
 19: (SB-IMPL::SUB-SUB-SERVE-EVENT NIL NIL)
 20: (SB-IMPL::SUB-SERVE-EVENT NIL NIL NIL)
 21: (SB-SYS:WAIT-UNTIL-FD-USABLE 0 :INPUT NIL T)
 22: (SB-IMPL::REFILL-INPUT-BUFFER #<SB-SYS:FD-STREAM for "standard input" {11AE4D99}>)
 23: (SB-IMPL::INPUT-CHAR/UTF-8 #<SB-SYS:FD-STREAM for "standard input" {11AE4D99}> NIL #:EOF-OBJECT)
 24: ((LAMBDA (&REST REST) :IN SB-IMPL::GET-EXTERNAL-FORMAT) #<SB-SYS:FD-STREAM for "standard input" {11AE4D99}> NIL #:EOF-OBJECT)
 25: (READ-CHAR #<SB-SYS:FD-STREAM for "standard input" {11AE4D99}> NIL #:EOF-OBJECT #<unused argument>)
 26: (READ-CHAR #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100EA651}> NIL #:EOF-OBJECT #<unused argument>)
 27: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100EA651}> NIL (NIL) T)
 28: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100EA651}> NIL (NIL) NIL)
 29: (READ #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100EA651}> NIL (NIL) NIL)
 30: (SB-IMPL::REPL-READ-FORM-FUN #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {100EA651}> #<unavailable argument>)
 31: (SB-IMPL::REPL-FUN NIL)
 32: ((LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL))
 33: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-IMPL::TOPLEVEL-REPL) {145F6945}>)
 34: (SB-IMPL::TOPLEVEL-REPL NIL)
 35: (SB-IMPL::TOPLEVEL-INIT)
 36: ((FLET #:WITHOUT-INTERRUPTS-BODY-42 :IN SB-EXT:SAVE-LISP-AND-DIE))
 37: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))

any tips? (running everything with SBCL 1.1.6.0-3c5581a on OSX 10.9.5)

Thank you!

**Comment by defaultxr** [comment]
A little late on this, but I think the problem here is that the bordeaux-threads library requires a newer version of SBCL. I was having a similar issue using an older version of SBCL previously because older versions ship with a version of ASDF which is not supported by bordeaux-threads (anything less than ASDF 3.1 is not supported, [as seen here](https://github.com/sionescu/bordeaux-threads/blob/92e6a89486a9469a36b4c0f73f4efc38f4ddeecc/bordeaux-threads.asd#L10)). I would suggest upgrading SBCL and seeing if that resolves the issue, if you're still having this problem.
