### ISSUE TITLE
exception in GraphDef_Recv: UGen 'ExpLin' not installed.

### ISSUE THREAD

**Issue by TatriX** [byulparan/cl-collider#102]
Hi!
Code bellow
```sclang
(proxy :exp-lin-test
       (poll.kr 1 (exp-lin 300 20 20000 0 1)))
```
gives an error:
```
exception in GraphDef_Recv: UGen 'ExpLin' not installed.
```

**Comment by byulparan** [comment]
`(exp-lin 300 20 20000 0 1)` is returned `0.39203042`. so `(proxy :exp-lin-test (poll.kr 1 (exp-lin 300 20 20000 0 1)))`
is work for me. but `exp-lin` is don't work with UGen(`exception in GraphDef_Recv: UGen 'ExpLin' not installed.`)

I will fix it asap. thanks!

**Comment by byulparan** [comment]
I fixed `lin-lin` `lin-exp` `exp-lin` `exp-exp`, and It needs many test.
