### ISSUE TITLE
Example on how to get left and right channel from multiout-ugen

### ISSUE THREAD

**Issue by bpostlethwaite** [byulparan/cl-collider#114]
I have a stereo signal and would like to pass left and right into `balance2.ar` but can't figure out how to separate the channels. In sclang it's an array index `sig[0]` and `sig[1]`.

Sorry if this is the wrong venue for such questions, happy to post or go elsewhere. Thanks, really amazing lib.

**Comment by defaultxr** [comment]
In cl-collider it's similar but they're lists instead of arrays. So you can use either `elt` or `nth`:

```lisp
(proxy :foo
       (let* ((s (sin-osc.ar (list 440 441)))
              (b (balance2.ar (elt s 0) (elt s 1))))
         (out.ar 0 b)))
```

**Comment by bpostlethwaite** [comment]
Much appreciated, thank you
