### ISSUE TITLE
Is cl-collider really only compatible with only supercollider 3.8 or 3.9?

### ISSUE THREAD

**Issue by jgarte** [byulparan/cl-collider#115]
Is cl-collider really [only compatible with only supercollider 3.8 or 3.9](https://github.com/byulparan/cl-collider#dependencies)?

**Comment by jgarte** [comment]
I have supercollider `3.12.1` for example

**Comment by byulparan** [comment]
I also run cl-collider with `3.12.1`. any problem?

**Comment by jgarte** [comment]
I packaged cl-collider recently for [guix](guix.gnu.org) but I'm running into some issue with supercollider being detected:

https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/lisp.scm#L1462

I think this might be a Guix issue regarding environment variables. I'll have to investigate it further.

Thanks for updating the README! I'll test soon with 3.12.1 and without guix.
