### ISSUE TITLE
LispWorks specific: the cleanup should be in "When quitting image"

### ISSUE THREAD

**Issue by Yehouda** [byulparan/cl-collider#124]
Currently, the quit cleanup is defined in the  "Confirm when quitting image"  action list:
https://github.com/byulparan/cl-collider/blob/d601c1b6ace8fb7cf6d1ee0862a85fd80441d1ab/server.lisp#L457

It should be in the "When quitting image" action list instead. 

The lists are documented (briefly) here:
http://www.lispworks.com/documentation/lw80/lw/lw-action-ug-6.htm

Also: 

1) The call  to **thread-wait** inside **server-quit** should be changed to **thread-wait-with-timeout** to avoid hanging. 
       https://github.com/byulparan/cl-collider/blob/d601c1b6ace8fb7cf6d1ee0862a85fd80441d1ab/server.lisp#L255
2) The call **bt:join-thread** inside **cleanup-server** should cbe changed to something that does not hang if domething goes wrong with the thread.
      https://github.com/byulparan/cl-collider/blob/d601c1b6ace8fb7cf6d1ee0862a85fd80441d1ab/server.lisp#L407

**Comment by byulparan** [comment]
I changed "When quitting image" for Lispworks, thanks.

but  improve about `server-quit` process needs time to think.
