### ISSUE TITLE
How to set up midi control?

### ISSUE THREAD

**Issue by kflak** [byulparan/cl-collider#148]
Hi,

Trying to set up midi to be able to control synth via a midi keyboard, but I can't find any documentation on the procedure. Is it even possible in cl-collider?

**Comment by kflak** [comment]
Great, thanks! Still getting used to the cl ecosystem :-) Will give the alsa-midi package a try.

**Comment by tentaclius** [comment]
> Great, thanks! Still getting used to the cl ecosystem :-) Will give the alsa-midi package a try.

It's a lot of fun!

Here is a repo of me fooling around with alsa-midi and cl-collider: https://github.com/tentaclius/cl-music/tree/main

By no mean a complete library, just some loosely coupled code. Most convenience definitions are in _init.cl_ and some examples with midi in _arturia-*.cl_ and _launchpad-*.cl_ (interacting with Arturia mkII and Novation Launchpad respectively).

**Comment by kflak** [comment]
Awesome! I am now at the point where I can get midi from reaper into cl, which I already count as a victory. Next step is to have it make some noise. Your repo is very useful reading...
