### ISSUE TITLE
sound-in

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#17]
in audioin.lisp
sound-in-prim should be 
 
(defun sound-in-prim (chan-offset bus mul add)
  (if (not (listp bus)) (sc::madd (in.**ar** (sc::add chan-offset bus) 1) mul add)
	(if (equal bus (loop repeat (length bus) for i from (car bus) collect i))
	    (sc::madd (in.**ar** (sc::add chan-offset (car bus)) (length bus)) mul add)
	    (sc::madd (in.**ar** (sc::add chan-offset bus)) mul add))))

**Comment by byulparan** [comment]
Thanks! It's fixed :-)
