### ISSUE TITLE
Quicklisp

### ISSUE THREAD

**Issue by defaultxr** [byulparan/cl-collider#23]
I think it would be convenient if cl-collider were available on [Quicklisp](https://www.quicklisp.org/beta/). It would be easier for users to install it, and it would let other projects depend on this library.

I think there are 3 main issues that would prevent cl-collider from being accepted into Quicklisp right now:

- [x] cl-collider uses its own `osc` package. Quicklisp also has an `osc` library available, and since they both share the same name, it may cause confusion or possible conflicts if users want to use the one on quicklisp. I think the best solution for this would be to rename cl-collider's `osc` package to `sc-osc` instead.

- [x] Quicklisp will not accept libraries that print warnings during compilation. Right now cl-collider prints some warnings. You can see these by running `(ql:quickload :sc :verbose t)` to load cl-collider. Here are the warnings I see on my system when I run that:

```
CL-USER> (ql:quickload :sc :verbose t)
To load "sc":
  Load 1 ASDF system:
    sc
; Loading "sc"
..
WARNING: redefining OSC::CAT in DEFUN
WARNING: redefining OSC::ENCODE-TYPETAGS in DEFUN
WARNING: redefining OSC:ENCODE-MESSAGE in DEFUN
WARNING: Implicitly creating new generic function OSC::ENCODE-ADDRESS-EXT.
WARNING: redefining OSC::ENCODE-DATA in DEFUN
WARNING: redefining OSC::DECODE-TAGED-DATA in DEFUN
WARNING: redefining OSC::ENCODE-INT64 in DEFUN
WARNING: redefining OSC::DECODE-UINT64 in DEFUN
WARNING: redefining OSC::ENCODE-BLOB in DEFUN
WARNING: redefining OSC::ENCODE-TIMETAG in DEFUN
WARNING: redefining OSC::DECODE-TIMETAG in DEFUN
WARNING: Implicitly creating new generic function FLEXI-STREAMS::READ-SEQUENCE*.
WARNING: Implicitly creating new generic function FLEXI-STREAMS::CHECK-IF-OPEN.
WARNING:
   Implicitly creating new generic function FLEXI-STREAMS::TRANSFORM-OCTET.
WARNING:
   Implicitly creating new generic function
   FLEXI-STREAMS:MAKE-IN-MEMORY-INPUT-STREAM.
WARNING:
   Implicitly creating new generic function
   FLEXI-STREAMS:GET-OUTPUT-STREAM-SEQUENCE.
WARNING:
   Implicitly creating new generic function
   FLEXI-STREAMS:OUTPUT-STREAM-SEQUENCE-LENGTH.
STYLE-WARNING:
   Generic function CLOSE clobbers an earlier FTYPE proclamation
   (FUNCTION (STREAM &KEY (:ABORT T)) (VALUES (MEMBER T) &OPTIONAL)) for the
   same name with (FUNCTION (T &KEY (:ABORT T)) *).
STYLE-WARNING:
   Generic function OPEN-STREAM-P clobbers an earlier FTYPE proclamation
   (FUNCTION (STREAM) (VALUES BOOLEAN &OPTIONAL)) for the same name with
   (FUNCTION (T) *).
WARNING: Implicitly creating new generic function FLEXI-STREAMS::READ-BYTE*.
WARNING: Implicitly creating new generic function FLEXI-STREAMS:UNREAD-BYTE.
WARNING: Implicitly creating new generic function FLEXI-STREAMS:PEEK-BYTE.
WARNING:
   Implicitly creating new generic function FLEXI-STREAMS::RESET-INPUT-STATE.
WARNING:
   Implicitly creating new generic function FLEXI-STREAMS::RESET-OUTPUT-STATE.
WARNING: Implicitly creating new generic function SC::CAT.
WARNING: Implicitly creating new generic function SC:SERVER-BOOT.
WARNING: Implicitly creating new generic function SC:SERVER-QUIT.
WARNING: Implicitly creating new generic function SC:BUFFER-FREE.
WARNING: Implicitly creating new generic function SC::SOURCE.
WARNING: Implicitly creating new generic function SC::NUM-OUTPUTS.
WARNING: Implicitly creating new generic function SC::OUTPUT-INDEX.
WARNING: Implicitly creating new generic function SC::COLLECT-CONSTANTS.
WARNING: Implicitly creating new generic function SC::OPTIMIZE-GRAPH.
WARNING:
   Implicitly creating new generic function SC::PERFORM-DEAD-CODE-ELIMINATION.
WARNING: Implicitly creating new generic function SC::MAKE-AVAILABLE.
WARNING: Implicitly creating new generic function SC::INPUT-SPEC.
WARNING: Implicitly creating new generic function SC::WRITE-DEF-UGEN-VERSION1.
WARNING: Implicitly creating new generic function SC::WRITE-DEF-UGEN-VERSION2.
WARNING: Implicitly creating new generic function SC::REPLACE-UGEN.
WARNING: Implicitly creating new generic function SC::CHECK-INPUTS.
WARNING: Implicitly creating new generic function SC::BUILD-SYNTHDEF.
WARNING: Implicitly creating new generic function SC::LOAD-SYNTHDEF.
WARNING: Implicitly creating new generic function SC::RECV-SYNTHDEF.
WARNING: redefining SC::OPTIMIZE-GRAPH in DEFGENERIC
WARNING: Implicitly creating new generic function SC::_RANGE.
WARNING: Implicitly creating new generic function SC::_EXP-RANGE.
WARNING: Implicitly creating new generic function SC::DUPLICATE.
WARNING: Implicitly creating new generic function SC:PVCALC.
WARNING: Implicitly creating new generic function SC:PVCALC2.
WARNING: Implicitly creating new generic function SC:PV-COLLECT.
WARNING: Implicitly creating new generic function SC::PV-COLLECT2.
WARNING: Implicitly creating new generic function SC:ENV-SHAPE-NUMBER.
WARNING: Implicitly creating new generic function SC::MINVAL.
WARNING: Implicitly creating new generic function SC:FOLD.
WARNING: Implicitly creating new generic function SC:WRAP.
WARNING: Implicitly creating new generic function SC:CLIP2.

(:SC)
```

Most of these warnings look like very minor issues that can be easily fixed without having to change much functionality of the library.

- [x] cl-collider depends on [scheduler](https://github.com/byulparan/scheduler). So scheduler would need to be added to quicklisp as well. I checked and it doesn't look like any warnings are printed for that library, so it should be easy to have it added to quicklisp.

If it's alright with you, I'd like to make these changes to cl-collider so it can be accepted on quicklisp. If that is okay, let me know and I'll submit a pull request here once I'm done.

Additionally, I would be willing to submit the request for scheduler and cl-collider to be included in quicklisp. Let me know if that is alright with you.

Thank you for making this library.

P.S. I'm also working on a [tutorial](https://github.com/defaultxr/cl-collider-tutorial) for using cl-collider. It's not done yet but I'm going to keep working on it.

**Comment by defaultxr** [comment]
Update on this: it looks like these are the only warnings I'm getting currently when loading this library with `(ql:quickload :sc :verbose t)`:

```
WARNING: redefining SC:QUANT in DEFUN
WARNING: redefining SC::POS in DEFUN
```

Otherwise, the other issues I mentioned seem to be solved now.

One last thing: I think it might be good to change the main name of the package and asdf system to `cl-collider` for consistency, but keep `sc` as the package nickname so functions can still be called like `sc:defsynth` after the library is loaded. It would probably be good to use the more descriptive project name when submitting to quicklisp.

**Comment by byulparan** [comment]
1. I was fixed redefining warning
2. I agree to your opnion, so I changed system/pakcage name to sc -> cl-collider.
   `sc` and `sc-user` possible too.
3. I added licence(Public Domain / 0-clause MIT) 
    just copy from `alexandria`

I will submit to quicklisp in next Monday :-) 
Thank you very much!

**Comment by defaultxr** [comment]
Awesome, sounds good! :)

Thank you!

**Comment by vrx** [comment]
great news, thanks !
