### ISSUE TITLE
cl-collider 3.9.0-rc1 segfaults when play macro is used

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#31]
Hello,

scsynth3.9 segfaults when trying to play a simple synth
(play (sin-osc.ar 440))
scsynth[13946]: segfault at ffffffffffffffff ip 00007fd8cfa50854 sp 00007fd8d4d0ab48 error 5 in IOUGens.so[7fd8cfa4e000+5000]

but

(defsynth sine-wave (&key (note 60))
  (let* ((freq (midicps note))
         (sig (sin-osc.ar [freq (+ freq 2)] 0 .2)))
     (out.ar 0 sig)))
(defparameter *synth* (sine-wave))

works fine

**Comment by byulparan** [comment]
set synthdef-version, before bootup server
```lisp
(setf sc::*synthdef-version* 2)
```
maybe "synthdefinition version 1" is deprecated in 3.9.
There seem to be many differences between 3.8 and 3.9, so I need more test to 3.9-dev.
