### ISSUE TITLE
Mapping a control bus to a synth's args

### ISSUE THREAD

**Issue by ntrocado** [byulparan/cl-collider#33]
I'm working through the examples in the Supercollider Book, using cl.
I'm having trouble translating how to route a control bus in real time.
The example is:
```
~kbus3 = Bus.control; // a control bus
~kbus4 = Bus.control; // a control bus
{Out.kr (~kbus3, SinOsc.kr(3).range(340, 540))}.play;
{Out.kr (~kbus4, LFPulse.kr(6).range(240, 640))}.play;
SynthDef("Switch", {arg freq = 440; Out.ar(0, SinOsc.ar(freq, 0, 0.3)) }).add
x = Synth("Switch"); //default
x.map(\freq, ~kbus3)
x.map(\freq, ~kbus4)
```
In cl I'm doing:
```
(defparameter *kbus3* (bus-control))
(defparameter *kbus4* (bus-control))
(play (out.kr *kbus3* (range (sin-osc.ar 3) 340 540)))
(play (out.kr *kbus4* (range (lf-pulse.kr 6) 240 640)))
(defsynth switch (&key (freq 440))
  (out.ar 0 (sin-osc.ar freq 0 0.3)))
(defparameter *x* (switch))
```

But what to do with the `map` part?

**Comment by defaultxr** [comment]
For now, you can do something like this:

```lisp
(sc::send-message *s* "/n_map" (sc::id *x*) "freq" (busnum *kbus3*))
(sc::send-message *s* "/n_map" (sc::id *x*) "freq" (busnum *kbus4*))
```

In the future I think I will update `ctrl` so that you'll be able to do something like this instead:

```lisp
(ctrl *x* :freq *kbus3*)
(ctrl *x* :freq *kbus4*)
```

But that doesn't work yet.

**Comment by ntrocado** [comment]
Thank you!
In fact, my first impulse was to use `ctrl`...

**Comment by defaultxr** [comment]
If my pull request #36 is accepted then you should be able to use `map-bus` to do this instead of having to use `send-message`. In the future I will also make it work correctly with `ctrl`.

**Comment by ntrocado** [comment]
Great!
