### ISSUE TITLE
should the synth function take node-id, group-id and position as arguments?

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#34]
it would be nice to be able to specify id, to and pos when creating a new synth with the synth function.
i wonder how to do that though as mixing &key and &rest is not quite recommended in cl.

my wish would be to be able to say for example
(defsynth mysynth ((amp 1) (freq 440)) (* amp (sin-osc.ar freq)))
(synth 'mysynth :to 2 :id 2000 :pos :after :amp 0.5)

and by the way how difficult would it be to be able to specify a ugen formula for a control parameter
like 
(synth 'mysynth :to 2 :id 2000 :pos :after :amp (lf-saw.kr 1) )

**Comment by defaultxr** [comment]
I think allowing you to specify `:to`, `:id`, etc, in `synth` should be possible. The `synth` function does not use `&key`. Its lambda list is `(name &optional args)`. But I think your syntax makes more sense, so I may change it to `(name &rest args)`. Then it should be easy to accept the other arguments you listed. I'll work on changing this when I'm able.

Providing a UGen as a synth's parameter would not be as simple as there would be some work behind the scenes required to make that happen. It does seem like a nice idea, though, so perhaps in the future.

**Comment by defaultxr** [comment]
Actually it looks like I was wrong about `synth` using `&optional`, I didn't realize byulparan had already changed that. The other change you mentioned should be pretty easy.
