### ISSUE TITLE
buffer-get-list fails when attempting to get a large range.

### ISSUE THREAD

**Issue by defaultxr** [byulparan/cl-collider#38]
To reproduce:

1. Load a large buffer:
`(defparameter buffer (buffer-read "/path/to/file.wav")`
2. Attempt to get a large number of samples from it. 1000 should be enough to trigger it:
`(buffer-get-list buffer 0 1000)`

I get an error that looks like this:

```
The bounding indices 0 and 4 are bad for a sequence of length 0.
   [Condition of type SB-KERNEL:BOUNDING-INDICES-BAD-ERROR]
See also:
  Common Lisp Hyperspec, bounding index designator [:glossary]
  Common Lisp Hyperspec, SUBSEQ-OUT-OF-BOUNDS:IS-AN-ERROR [:issue]

Restarts:
 0: [ABORT] abort thread (#<THREAD "OSC device receive thread" RUNNING {10025EF053}>)

Backtrace:
  0: (SB-KERNEL:VECTOR-SUBSEQ* #<unavailable argument> #<unavailable argument> #<unavailable argument>)
  1: ((LAMBDA (SC-OSC::X) :IN SC-OSC::SC-DECODE-TAGED-DATA) 102)
  2: ((FLET SB-IMPL::F :IN SB-IMPL::VECTOR-MAP-INTO/SIMPLE-VECTOR) 102)
  3: (SB-KERNEL:%MAP-FOR-EFFECT-ARITY-1 #<CLOSURE (FLET SB-IMPL::F :IN SB-IMPL::VECTOR-MAP-INTO/SIMPLE-VECTOR) {7FFFF546656B}> #(105 105 105 102 102 102 ...))
  4: (SB-KERNEL:%MAP NIL #<CLOSURE (FLET SB-IMPL::F :IN SB-IMPL::VECTOR-MAP-INTO/SIMPLE-VECTOR) {7FFFF546656B}> #(105 105 105 102 102 102 ...)) [more]
  5: (SB-IMPL::VECTOR-MAP-INTO/SIMPLE-VECTOR #(#(0 0 0 0 0 0 ...) #(0 0 1 149 59 180 ...) #(59 180 0 0 60 155 ...) #(60 155 0 0 59 211 ...) #(59 211 0 0 60 149 ...) #(60 149 128 0 59 233 ...) ...) 0 408 #<..
  6: (SC-OSC::SC-DECODE-TAGED-DATA #(44 105 105 105 102 102 ...))
  7: (SC-OSC::DECODE-MESSAGE #(47 98 95 115 101 116 ...))
  8: ((LAMBDA NIL :IN SC-OSC::MAKE-LISTENING-THREAD))
  9: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 10: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 11: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 12: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 13: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
 14: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFF5466D4B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 15: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "OSC device receive thread" RUNNING {10025EF053}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10025EEFF..
 16: ("foreign function: call_into_lisp")
 17: ("foreign function: new_thread_trampoline")
```

It seems to be a problem with the OSC code.

**Comment by byulparan** [comment]
It needs some solution.
currently, I has set maximum receive message buffer size to 2048 bytes.  
maybe It can increase until `usocket:+max-datagram-packet-size+` and I will it.
but you want get more large number of samples, you should write file from buffer,
then read that file.  (maybe you need https://github.com/byulparan/cl-sndfile)
UDP socket has limit packet-size(It same to sclang)....
but I have no plan include cl-sndfile to cl-collider.

**Comment by ntrocado** [comment]
I think the possibility that you mention, with a temporary file, is easy to do in a portable way and without extra libraries, because `buffer-write` can write a .raw (headerless) file, and `uiop` has a facility to deal with temporary files.

I'm thinking about something like this:

```
(defun buffer-get-list-using-file (buffer &key (start 0) frames action)
  "Write BUFFER to a temporary file, then load the values back into a list and return it. The values are from index START and for the number of FRAMES, if provided, or otherwise until the end of the buffer. ACTION is a function which will be passed the resulting list as an argument and evaluated once the file has been read."
  (uiop:with-temporary-file (:stream file
			     :pathname path
			     :type "raw"
			     :element-type '(unsigned-byte 32))
    (buffer-write buffer path :format :float :frames (or frames -1) :start-frame start)
    (file-position file 0)
    (let ((result (loop for frame = (read-byte file nil)
			while frame
			collect (ieee-floats:decode-float32 frame))))
      (if action
	  (funcall action result)
	  result))))
```

But I'm unsure how it would be better to implement this. Either:

1.  Have two different functions. This is how it is in sclang, where there's `getn` which is limited by packet size, `loadToFloatArray` which works with a temporary file, and `getToFloatArray` which uses a series of getn messages, is slow and unreliable, but works when the server is on a remote machine. Anyway, having three different names for what is essentially the same purpose is not the most intuitive thing...
1. Use just a single `buffer-get-list` function, but with a keyword `:strategy` to select the desirable retrieving method.
1.  ?...

Thoughts?

**Comment by byulparan** [comment]
I think first option is better and 3 functions need. 
`getn(buffer-get-list)`, `loadToFloatArray(buffer-get-list-using-file)`, 
`getToFloatArray(buffer-get-list-.....)`.  `getToFloatArray` also need for remote machine, right?

**Comment by defaultxr** [comment]
I wrote a function like sclang's `getToFloatArray`, but hadn't gotten around to submitting it yet:

```lisp
(defun buffer-get-range (buffer &optional (start 0) (end (slot-value buffer 'sc::frames)))
  "Get an array of the frames of BUFFER. Unlike `buffer-get-list', this function is not limited by OSC packet size and can return any number of frames, though it may be slower."
  (loop :while (< start end)
     :append
       (let ((dec (min 400 (- end start))))
         (prog1
             (buffer-get-list buffer start dec)
           (incf start dec)))))
```

Feel free to add it now, and rename it if you'd like. Otherwise I'll likely submit it as a PR at some point (along with some code I wrote for loading files wavetables).

**Comment by ntrocado** [comment]
I'll submit a PR now with what I have… looking forward to @defaultxr 's contributions!
Incidentally I investigated whether it would be possible to use the same temporary file method to *set* values in a buffer as well. AFAIK this is not possible yet because `/b_read` doesn't work with .raw files (the server doesn't read all the formats that it can write).

**Comment by byulparan** [comment]
I was add @ntrocado's PR(thank you!).
next, I will add @defaultxr's `buffer-get-range`'s implementation
to `buffer-get-list` and It control via keyword option.

**Comment by byulparan** [comment]
I added @defaultxr's `buffer-get-range` and some buffer api renamed.
buffer-get-list -> `buffer-getn` , buffer-set-list -> `buffer-setn`.
add `buffer-load-to-list`(buffer-get-list-using-file),
`buffer-get-to-list`(buffer-get-range).

please report bug or problem. Thanks!

**Comment by defaultxr** [comment]
Seems this is solved with `buffer-load-to-list` and `buffer-get-to-list` functions, so I'm closing this... Of course, if anyone thinks more needs to be done here, feel free to comment!
