### ISSUE TITLE
How to define these type of ugens?

### ISSUE THREAD

**Issue by azimut** [byulparan/cl-collider#43]
https://github.com/redFrik/f0plugins/blob/5e684d755b6576f99331995f59f33cade61bfda6/source/Nes2/sc/Nes2.sc#L15

```
Nes2Square {
	*ar {|trig= 0, dutycycle= 0, loopenv= 0, envdecay= 0, vol= 10, sweep= 0, sweeplen= 0, sweepdir= 0, sweepshi= 0, freq= 100, vbl= 0|
		var a0, a1, a2, a3;
		a0= Clip.kr(dutycycle.round, 0, 3)*64;
		a0= a0|(Clip.kr(loopenv.round, 0, 1)*32);
		a0= a0|(Clip.kr(envdecay.round, 0, 1)*16);
		a0= a0|Clip.kr(vol.round, 0, 15);
		a1= Clip.kr(sweep.round, 0, 1)*128;
		a1= a1|(Clip.kr(sweeplen.round, 0, 7)*16);
		a1= a1|(Clip.kr(sweepdir.round, 0, 1)*8);
		a1= a1|Clip.kr(sweepshi.round, 0, 7);
		a2= freq.max(0).round%256;
		a3= Clip.kr((freq/256).floor, 0, 7);
		a3= a3|(Clip.kr(vbl.round, 0, 31)*8);
		^Nes2.ar(trig, a0, a1, a2, a3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1)
	}
	*categories {^#["UGens>Emulators"]}
}
```

Not sure how to define this or if it is a ugen or something I can do with defsynth. It looks like it uses SC "|" (bitwise or) which I don't see on cl-collider ugens. Please help.

**Comment by defaultxr** [comment]
In Lisp, you'd use `logior` for bitwise or. It looks like cl-collider already has support for it when compiling synthdefs. I'm going to try translating this pseudo-ugen into Lisp to see if it works.

**Comment by azimut** [comment]
Thank you! The code you provided worked fine on a defsynth+out.ar (defugen failed, probably not the place to define things with "let" using sc operators, like multiplying a number by a ugen) and I have sound now.
