### ISSUE TITLE
Windows paths

### ISSUE THREAD

**Issue by ntrocado** [byulparan/cl-collider#50]
Even though I have SuperCollider installed in the default directories, quickloading cl-collider was failing on my system, because the paths for plugins and synthdefs are set relative to the home directory ("~/"), and assuming that this directory is the same as %userprofile%, which wasn't the case. 

Due to the complications (to say the least…) of configuring "home" in Windows, because often the os, emacs, sbcl and quicklisp don't agree on its location, do you think it's better to use the strategy below (with `uiop:get-folder-path :local-appdata`)? It should spare most Windows users from having to manually edit server.lisp before using the library.

```diff
   server.lisp
@@ -16,12 +16,14 @@
   #+linux (list "/usr/local/lib/SuperCollider/plugins/"
 		"/usr/local/share/SuperCollider/Extensions/")
   #+windows (list "c:/Program Files/SuperCollider-3.9.3/plugins/"
-		  "~/AppData/Local/SuperCollider/Extensions/"))
+		  (full-pathname (merge-pathnames #P"SuperCollider/Extensions/"
+						  (uiop:get-folder-path :local-appdata)))))
 
 (defvar *sc-synthdefs-path*
   #+darwin (full-pathname "~/Library/Application Support/SuperCollider/synthdefs")
   #+linux (full-pathname "~/.local/share/SuperCollider/synthdefs/")
-  #+windows (full-pathname "~/AppData/Local/SuperCollider/synthdefs/")
+  #+windows (full-pathname (merge-pathnames #P"SuperCollider/synthdefs/"
+					    (uiop:get-folder-path :local-appdata)))
   "The directory where the scsyndef files for synthdefs are saved.")
```

Let me know if a PR is welcomed.

**Comment by byulparan** [comment]
Thank you and I fully agree. please send PR! :-)

**Comment by ntrocado** [comment]
Thank you for this great library, btw!
