### ISSUE TITLE
full-pathname pb when directory do not exist

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#52]
In server.lisp
```

(defvar *sc-synthdefs-path*
  #+darwin (full-pathname "~/Library/Application Support/SuperCollider/synthdefs")
  #+linux (full-pathname "~/.local/share/SuperCollider/synthdefs/")
  #+windows (full-pathname "~/AppData/Local/SuperCollider/synthdefs/")
  "The directory where the scsyndef files for synthdefs are saved.")
```

can actually yield some problems as full-pathname will produce an error if the directory does not exist.
it is moreover a bit tricky to spot, so probably at least an informative warning should be printed.
one solution of course is to:
mkdir -p ~/.local/share/SuperCollider/synthdefs/

**Comment by defaultxr** [comment]
The error message given when a path is missing is indeed cryptic.

Thought: a simple solution might be to check for the path's existence in the `full-pathname` function, and give a more helpful error or warning there.

Maybe `full-pathname` could be simplified to something like this?

```lisp
(defun full-pathname (path)
  "Get the absolute path name of PATH, erroring if it does not exist."
  (let ((truename (uiop:truename* path)))
    (if truename
        (namestring truename)
        (error "The file or directory ~s does not exist." path))))
```

For reference, the current version is:

```lisp
(defun full-pathname (path)
  "returning absoulte full-pathname of path"
  (let* ((directory (uiop:truename* (uiop:pathname-directory-pathname path)))
	 (filename (pathname-name path))
	 (filetype (pathname-type path)))
    (when directory
      (format nil "~a~@[~a~]~@[.~a~]" (namestring directory) filename filetype))))
```

My version is simpler, but I'm not sure if there is some reasoning behind the current version that I'm not seeing.
