### ISSUE TITLE
"with-rendering" not working?

### ISSUE THREAD

**Issue by ntrocado** [byulparan/cl-collider#54]
I get an error if the output file doesn't exist yet:

> ; Debugger entered on #<TYPE-ERROR expected-type:
> ;              (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME FILE-STREAM)
> ; 
> ;              datum: NIL>
> 
> 

If I create a blank file then I get:

> There is no applicable method for the generic function
>   #<STANDARD-GENERIC-FUNCTION CL-COLLIDER::SC-REPLY-THREAD (1)>
> when called with arguments
>   (#<CL-COLLIDER::NRT-SERVER {10064E0123}>).
> 

There's also a style warning:

> ; caught STYLE-WARNING:
> ;   The function has an odd number of arguments in the keyword portion.
> 

This is about [this line](https://github.com/byulparan/cl-collider/blob/2cfc5771be4edec0c3da653e5d86339c4adee917/server.lisp#L439). I think it's just missing the `:id` keyword.

**Steps to reproduce:** follow the instructions on README.
**System:** Win10, SBCL, Sly, Supercollider 3.9.3

**Comment by ntrocado** [comment]
Actually the output file error is already fixed by the last commits. Sorry…
I still get the other errors though.

**Comment by justin2004** [comment]
@ntrocado 

i did find a quick patch you can apply to allow with-rendering to work for bodies that do not require scheduling:



diff --git a/server.lisp b/server.lisp
index 91179dc..9d2f185 100644
--- a/server.lisp
+++ b/server.lisp
@@ -436,7 +436,7 @@
     `(let* ((,file-name (full-pathname ,output-files))
            (,osc-file (cat (subseq ,file-name 0 (position #\. ,file-name)) ".osc"))
            (*s* (make-instance 'nrt-server :name "NRTSynth" :streams nil)))
-       (make-group 1 :pos :head :to 0)
+       (make-group :id 1 :pos :head :to 0)
        ,@body
        (when ,pad (send-bundle *s* (* 1.0d0 ,pad) (list "/c_set" 0 0)))
        (with-open-file (,non-realtime-stream ,osc-file :direction :output :if-exists :supersede
@@ -552,7 +552,7 @@
       (let* ((group-id (if id id (incf new-group-id)))
             (group (make-instance 'group :server server :id group-id :pos pos :to target-id)))
        (message-distribute group (list "/g_new" group-id (node-to-pos pos) target-id) server)
-       (sync)
+       ;(sync)
        group))))

 (defun server-query-all-nodes (&optional (rt-server *s*))








then something like:

(defsynth sindrum ((freq 900) (pos 0) (level 1.0))
  (let* ((env (env-gen.kr (perc 0.001 level) :act :free))
         (sig (lpf.ar (sin-osc.ar freq 0 1) (* freq env))))
    (out.ar 0 (pan2.ar sig pos 0.2))))

; the body of with-rending cannot have a callback within it right now
; because nrt-server does not have a scheduler
(with-rendering ("/home/justin/some.aiff" :pad 6 :keep-osc-file t)
   (synth 'sindrum))

**Comment by ntrocado** [comment]
This works, thank you!
I had to do some changes to have correct pathnames on Windows…
Also I wonder if the `(sync)` line is useful for something else. I did some testing and apparently there's no issue when creating groups, etc.

**Comment by defaultxr** [comment]
I submitted the changes mentioned by @justin2004 in PR #69 . Are there any other issues remaining with `with-rendering` now that those changes have been merged?

**Comment by ntrocado** [comment]
I had to make the following changes in order for the nrt server to work with Windows. At the moment I don't have a machine with Linux or macOS so I can't test if this patch breaks things for other OSes.

```diff
modified   server.lisp
@@ -455,14 +455,17 @@
 	     (write-sequence (osc::encode-int32 (length ,message)) ,non-realtime-stream)
 	     (write-sequence ,message ,non-realtime-stream))))
        (sc-program-run (full-pathname *sc-synth-program*)
-		               (list "-U" (format nil "~{~a~^:~}" (mapcar #'full-pathname *sc-plugin-paths*))
-			                 "-N" ,osc-file
-			                 "_" ,file-name ,(write-to-string sr) (string-upcase (pathname-type ,file-name))
-			                 (ecase ,format
-			                   (:int16 "int16")
-			                   (:int24 "int24")
-			                   (:float "float")
-			                   (:double "double"))))
+		       (list "-U" (format nil
+					  #-windows "~{~a~^:~}"
+					  #+windows "~{~a~^;~}"
+					  (mapcar #'full-pathname *sc-plugin-paths*))
+			     "-N" ,osc-file
+			     "_" ,file-name ,(write-to-string sr) (string-upcase (pathname-type ,file-name))
+			     (ecase ,format
+			       (:int16 "int16")
+			       (:int24 "int24")
+			       (:float "float")
+			       (:double "double"))))
        (unless ,keep-osc-file
 	 (delete-file ,osc-file))
        (values))))
modified   synthdef.lisp
@@ -89,7 +89,8 @@
   synthdef)
 
 (defun write-synthdef-file (name encoded-synthdef)
-  (let ((path (make-pathname :directory (full-pathname *sc-synthdefs-path*) :name name :type "scsyndef")))
+  (let ((path (merge-pathnames (make-pathname :name name :type "scsyndef")
+			       (full-pathname *sc-synthdefs-path*))))
     (with-open-file (stream path :direction :output
 				 :if-exists :supersede
 				 :element-type '(unsigned-byte 8))
```

Also the scheduler doesn't work with the nrt server.
