### ISSUE TITLE
buffer copy

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#58]
I found it very useful to add a copy-buffer function (way faster than getting and setting)
something like that
(defun copy-buffer (bufnum-src bufnum-dst start-dst start-src nframes)
	(apply #'send-message
				 *s*
				 (append (list "\b_gen" bufnum-dst "copy" start-dst bufnum-src start-src nframes)))
	(sync *s*)
	)

**Comment by byulparan** [comment]
ok! it looks useful. I will add this function(maybe function name will change)

**Comment by byulparan** [comment]
add `buffer-copy`.
