### ISSUE TITLE
Compilation fails ....

### ISSUE THREAD

**Issue by the-drunk-coder** [byulparan/cl-collider#6]
Hi,

when trying to load cl-collider with quicklisp `(ql:quickload "sc")`, i get the following error message:

```
no symbol named "NOW" in "SCHEDULER"
   [Condition of type SB-KERNEL:SIMPLE-PACKAGE-ERROR]
```

Scheduler and Simple-Utils are both present and can be loaded ... 

Any hints ?

**Comment by byulparan** [comment]
ah! sorry... It was change internally. plz.. wait until this weekend. 
I'll maintain to cl-collider again....:-<
