### ISSUE TITLE
ecl, pileup problem

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#63]
CL-COLLIDER> (setf *s* (make-external-server "localhost" :port 48800))

Condition of type: UNBOUND-VARIABLE
The variable PILEUP::%SIZE is unbound.

**Comment by byulparan** [comment]
run ECL without cl-collider.

```lisp
(ql:quickload :pileup)

(defclass foo ()
  ((in-queue :initform (pileup:make-heap #'<)
	     :reader in-queue)))
```

I evaluated this code, `(make-instance 'foo)` is run ok.

but when I compiled this code, then I get 
```
;;; Compiling (DEFCLASS FOO ...).
;;; Style warning:
;;;   in file ecl-swank-tmpfile-IJVNO6, position 0
;;;   at (DEFCLASS FOO ...)
;;;   ! Variable %SIZE was undefined. Compiler assumes it is a global.
;;; Emitting code for #:LAMBDA0.
```
and 
```lisp
(make-instance 'foo)

The variable PILEUP::%SIZE is unbound.
   [Condition of type UNBOUND-VARIABLE]
```

It seems not cl-collider's problem. maybe It's problem of ECL with Pileup.
so I can't solve this problem. or I should be find alternative of pileup.

**Comment by vrx** [comment]
Thanks for your answer, and yes, it really looks like a problem with pileup.

I asked the ecl dev community (but no answers yet)
[https://gitlab.com/embeddable-common-lisp/ecl/-/issues/633 ](https://gitlab.com/embeddable-common-lisp/ecl/-/issues/633 )

And posted as well on the pileup github page
[https://github.com/nikodemus/pileup/issues/3](https://github.com/nikodemus/pileup/issues/3)

I looked at the code but cannot really understand where this %SIZE variable is coming from - if i try to set it up like 
(setf PILEUP::%SIZE 10)
(setf PILEUP::%KEY 10)
I get other type of problems (connected to threading, which does not sound so good)...

Do you have ideas for a possible replacement ?

**Comment by vrx** [comment]
there are many implementations of binary heap in cl actually

https://github.com/phoe/damn-fast-priority-queue/blob/main/priority-queue-benchmark/README.md


I tested this one
https://github.com/TheRiver/CL-HEAP
and tests passed on ECL

there is also a thread-safe implementation (same name different code...)
https://github.com/zerth/cl-heap

and also this implementation (seem to be the newest)
https://quickref.common-lisp.net/heap.html

**Comment by byulparan** [comment]
ecl use `cl-heap` instead `pileup`. If fix to problem `pileup` with `ecl` then ecl use `pileup` again.
please test & report cl-collder with ecl.

this issue will close.

**Comment by byulparan** [comment]
ecl fixed issue with `pileup` (https://gitlab.com/embeddable-common-lisp/ecl/-/issues/633)
ecl reuse `pileup`.

**Comment by vrx** [comment]
yes many thanks, sound is flowing : - )
