### ISSUE TITLE
unable to boot server

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [byulparan/cl-collider#66]
Hi! 

Just starting out with the tutorials. This issue comes up when attempting `(server-boot *s*)`.
Running on SBCL 1.4.16 and SLIME 2.23.

Looking forward to do some interesting livecoding! :)

```
Subprocess with command "\"/usr/local/bin/scsynth\" -u 40555 -c 16384 -a 1024 -i 2 -o 2 -z 64 -S 0 -b 1024 -n 1024 -d 1024 -m 8192 -w 64 -r 64 -D 1 -R 1 -l 1 -V 0 -U \"/usr/local/lib/SuperCollider/plugins/:/usr/local/share/SuperCollider/Extensions/\" "
 exited with error code 1
   [Condition of type UIOP/RUN-PROGRAM:SUBPROCESS-ERROR]

Restarts:
 0: [CONTINUE] IGNORE-ERROR-STATUS
 1: [ABORT] abort thread (#<THREAD "scsynth" RUNNING {1005568853}>)

Backtrace:
  0: (UIOP/RUN-PROGRAM::%CHECK-RESULT 1 :COMMAND "\"/usr/local/bin/scsynth\" -u 40555 -c 16384 -a 1024 -i 2 -o 2 -z 64 -S 0 -b 1024 -n 1024 -d 1024 -m 8192 -w 64 -r 64 -D 1 -R 1 -l 1 -V 0 -U \"/usr/local/l..
  1: (UIOP/RUN-PROGRAM::%USE-SYSTEM "\"/usr/local/bin/scsynth\" -u 40555 -c 16384 -a 1024 -i 2 -o 2 -z 64 -S 0 -b 1024 -n 1024 -d 1024 -m 8192 -w 64 -r 64 -D 1 -R 1 -l 1 -V 0 -U \"/usr/local/lib/SuperColli..
  2: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
  3: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  4: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  5: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
  6: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
  7: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7F90AF07EDCB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
  8: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "scsynth" RUNNING {1005568853}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10055687FB}> NIL)
  9: ("foreign function: call_into_lisp")
 10: ("foreign function: new_thread_trampoline")
```

**Comment by defaultxr** [comment]
Hi. Can you try running this command from a shell directly to see what output you get?

`/usr/local/bin/scsynth -u 40555 -c 16384 -a 1024 -i 2 -o 2 -z 64 -S 0 -b 1024 -n 1024 -d 1024 -m 8192 -w 64 -r 64 -D 1 -R 1 -l 1 -V 0 -U "/usr/local/lib/SuperCollider/plugins/:/usr/local/share/SuperCollider/Extensions/"`

My guess is maybe one of those extension directories doesn't exist on your system, in which case you'd need to manually set `*sc-plugin-paths*`. I just do `(setf *sc-plugin-paths* nil)` and it works for me.

If you run the command from a shell and it works fine, maybe check your `*inferior-lisp*` buffer in Emacs to see if the output from scsynth shows up there when you get this error.

**Comment by 4lph4-Ph4un** [comment]
Hi! Tried running from shell and what I got was this:

```
*** ERROR: open directory failed '/home/Timsa/.local/share/SuperCollider/synthdefs'
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
Cannot create RT messagebuffer thread: Operation not permitted (1)
Retrying messagebuffer thread without RT scheduling
Messagebuffer not realtime; consider enabling RT scheduling for user
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
control open "hw:0" (No such file or directory)
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1700:(_snd_pcm_hw_open) Invalid value for card
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
JackTemporaryException : now quits...
Cannot initialize driver
JackServer::Open failed with -1
```

**Comment by defaultxr** [comment]
I don't really know much about WSL but maybe that has something to do with these errors? The JACK and ALSA errors in your paste are what make me guess that. Are you running JACK in WSL as well? On Linux you have to add yourself to the `audio` group to have the ability to run programs in realtime which is needed by programs like JACK and SC. WSL might have the same requirement.

Is there any reason you're running SC in WSL instead of on Windows directly? SC and Emacs both have Windows versions which might be easier. Never tried any of them though so I can't really say for sure.

**Comment by 4lph4-Ph4un** [comment]
Thanks! I'll start checking the possible issues with JACK. 

The reason I'm running this on WSL is that I have most of my other language setups and projects set so that are better developed on WSL/Linux and for that reason my Win 10 Emacs/Slime configurations always lag a bit behind. I mainly do all my clisp work on linux as well so that's why I haven't bothered to setup this directly on Windows side. 

I can look up whether WSL comes into play with this and messes things up and report back. But I'll start by checking if my JACK configs need some work :) If WSL is an issue that has no workarounds then I guess I'll have to jump to Win with cl-collider. If not, good. If there's workarounds I'll let you know so others like me have some info on it.

**Comment by defaultxr** [comment]
Sounds good. I know basically nothing about WSL, and I almost never use Windows, so everything I said is really just a best guess based on your paste and could be totally wrong. Looking forward to hearing what you find out regardless though, thanks.

**Comment by justin2004** [comment]
@4lph4-Ph4un, 
have you tried to run scide.exe?
and then just execute     s.boot;    within it?

also, if your host OS is *nix why not just run cl-collider and scsynth on *nix directly?
that is how i do it.

**Comment by 4lph4-Ph4un** [comment]
@justin2004 
It seems the problem lies at the JACK after some debugging. I need to configure it properly so it will work on WSL (Think I'll be able to work this through - though let it be said that proper audio support for WSL out of the box wouldn't be bad at all).

> also, if your host OS is *nix why not just run cl-collider and scsynth on *nix directly?
that is how i do it.

The host system for the current configuration is Windows 10. It's just that all the CLisp, Haskell and Python coding are currently done in WSL on this particular machine.

**Comment by 4lph4-Ph4un** [comment]
Okay, since WSL doesn't really provide an easy access to sound for now and the configuration to overcome that would be too much (setting up PulseAudio server to win10 side, a client with specific multithreading version on WSL and then configure Jack to work with Pulse - no thanks.. I gave up after one day) I decided to update my Windows side of CLisp development.

Now what I get is this on `make-external-server`:

```lisp
SC-USER> (setf *s* (make-external-server "localhost" :port 40555))
; Evaluation aborted on #<TYPE-ERROR expected-type:
             (OR (VECTOR CHARACTER) (VECTOR NIL) BASE-STRING PATHNAME STREAM)
             datum: NIL>.
```
