### ISSUE TITLE
Weird error output when using tempo-clock

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [byulparan/cl-collider#68]
Hi! I've been trying to study cl-collider and a simple test with tempo-clock resulted in a weird error. The sound is audible but I get this on my slime REPL:

```
Error "The value #<CL-COLLIDER::NODE :server #<CL-COLLIDER::EXTERNAL-SERVER localhost-127.0.0.1:4444> :id 1032 :name "foo"> is not of type SYMBOL" in Tempo-Clock thread
```

Here's the code:

```lisp
(setf *s* (make-external-server "localhost" :port 4444))
(server-boot *s*)


(clock-bpm 60)

(defsynth foo ((freq 220) (dur 1) (gain 1) (pan 0))
  (let* ((env (line.kr .2 .0 dur :act :free))
         (sig (sin-osc.ar freq 0 env)))
    (out.ar 0 (pan2.ar sig pan gain))))

;; NOTE: For testing 1 hit:
(at-beat (clock-quant 4) (synth 'foo :freq 220 :dur (clock-tm 5))

(defun syncd-seq (beat &optional (dur 1) (i 0))
  (at-beat beat (synth 'foo :dur (clock-tm .5) :gain .5))
  (let* ((next (+ beat dur)))
    (clock-add next 'syncd-seq next dur (+ i 1))))

;; NOTE: 4ths:
(syncd-seq (clock-quant 4))
```

Am I doing something completely stupid or is this a proper error on some obscure behavior? :)

Running on:

Windows 10, SBCL 1.4.14

**Comment by ntrocado** [comment]
I don't know what causes the error (sorry), but I couldn't reproduce it - I'm on the same OS/SBCL version. I just run your code and other than a missing `)` after `(at-beat (clock-quant 4) (synth 'foo :freq 220 :dur (clock-tm 5))` there were no errors printed, and sound come out correctly.

**Comment by 4lph4-Ph4un** [comment]
Hi! I've updated sc-collider and it seems that some of the API has changed (`clock-tm` to `clock-dur` at least). Has something else changed too. I modified my issue example to the current signature but now it seems `at-beat` makes no sound. The error itself has vanished:

```lisp
(setf *s* (make-external-server "localhost" :port 4444))

(server-boot *s*)


(clock-bpm 60)

(defsynth foo ((freq 220) (dur 1) (gain 1) (pan 0))
  (let* ((env (line.kr .2 .0 dur :act :free))
         (sig (sin-osc.ar freq 0 env)))
    (out.ar 0 (pan2.ar sig pan gain))))

;; NOTE: Sound is OK!
(synth 'foo :freq 220 :dur (clock-dur 1/4))

;; NOTE: For testing 1 hit (Nothing out):
(at-beat (quant 4) (synth 'foo :freq 220 :dur (clock-dur 5)))

(defun syncd-seq (beat &optional (dur 1) (i 0))
  (at-beat beat (synth 'foo :dur (clock-dur 1/2) :gain .5))
  (let* ((next (+ beat dur)))
    (clock-add next 'syncd-seq next dur (+ i 1))))

;; NOTE: 4ths (Nothing out either):
(syncd-seq (quant 4))
```

**Comment by byulparan** [comment]
use `clock-quant` instead `quant`.

**Comment by 4lph4-Ph4un** [comment]
Thanks! This works and no weird errors either! :)
