### ISSUE TITLE
Export PATH?

### ISSUE THREAD

**Issue by ntrocado** [byulparan/cl-collider#72]
The symbol `path`, for the accessor to the path of a file loaded in a buffer, isn't exported. Is there a reason for this?

**Comment by defaultxr** [comment]
It seems like `path` might be a common name for a function so there could be conflicts. That is the only drawback I can see to exporting. Though I don't imagine someone using cl-collider will also be using another library in the same image that isn't aware of the function being exported.

I'm using cl-collider in the same image as [Incudine](http://incudine.sourceforge.net) as well as a bunch of my own projects and none of them export a `path` symbol. Seems like a good sign that exporting wouldn't cause issues.
