### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by defaultxr** [byulparan/cl-collider#8]
Hi,

First of all, thanks for writing this library! I've been writing a library of my own, [cl-patterns](https://github.com/defaultxr/cl-patterns), which uses cl-collider as a backend. My library is based off of SuperCollider's patterns system and it's built for sequencing. It's still in early stages and doesn't have a lot of features yet but your library has made it possible.

I've been using cl-collider and in the process I made a few changes to my fork before I realized you were updating this one again. Since you're still developing this, I'd like to suggest a few changes to cl-collider that I'd like to contribute to the project, if you're interested. 

1. There are a few grammar errors in the english in this library and I'd be willing to fix those for you and submit the changes as a pull request.

2. For consistency, I think the library should try to use SuperCollider's names for functionality. For example, having `free` and `release` functions instead of using `bye` to stop synths. `free` could be a generic function with methods for buffers, synths, and proxies. Additionally, it may be best to continue to use names like `sin-osc.ar` instead of `sin-osc` for ugen consistency and to avoid possible name clashes for ugens with common names like `out.ar`.

3. Have a `synth` function instead of generating specific functions for each synth. This would make it easier to start synths programmatically, i.e. from my patterns system. That way, it's not necessary to use `apply` to call an arbitrary synth from a function. I've already written this function in my fork of cl-collider [here](https://github.com/defaultxr/cl-collider.old/blob/master/synthdef.lisp#L223). It uses a function called `make-synth-msg-2` which eliminates need for using `apply` for synth arguments. It's defined [here](https://github.com/defaultxr/cl-collider.old/blob/master/server.lisp#L127).

4. Make a separate `sc-user` package for the user to use instead of being in `sc` directly. That way, if you still want to keep the functions generated for each synth, they can be defined in `sc-user` instead of `sc` and reduce the chance of clashing with already-existing functions in `sc`.

5. Use [named-readtables](https://github.com/melisgl/named-readtables) for the `#!` and `[` syntaxes and any other syntax shortcuts, and make them available in `sc-user` instead of globally, so that libraries that require cl-collider won't automatically have it added to their readtables.

Let me know if you'd be interested in these changes, and I'd be more than happy to start contributing them so that cl-collider is even better for users and works even better for libraries that build off of your work. Thanks again.

**Comment by vrx** [comment]
+1 for keeping .ar syntax

**Comment by byulparan** [comment]
Thanks for very useful suggestion, and Sorry for late response(recently,I was busy..)
I will update from your almost suggestion. 
1. Thank you!  English are alway problem for me (include this comment..)
2. OK. I will update it, include  <code>.ar</code> syntax.  
3. <code>synth</code> are very good idea. I will check your code, and update it! 
4. <code>sc-user</code> package is need, but I think It should be create by user for each environment, PATH, setup. 
5. I'm not friendly to named-readtables, so I need some exprience with that.

Thanks again!!

**Comment by defaultxr** [comment]
Awesome! Thank you for the response. Everything you said makes sense for me and I agree. For the English fixes, I opened a pull request [here](https://github.com/byulparan/cl-collider/pull/11). It also has a few other minor fixes in it which I documented in the comment there.

**Comment by byulparan** [comment]
I merged your request patch! Thank you!   Other suggestions also will update, as soon as possible!

**Comment by defaultxr** [comment]
These suggestions have all been implemented so I'm going to close this issue :)
