### ISSUE TITLE
Plotting and debugging

### ISSUE THREAD

**Issue by TatriX** [byulparan/cl-collider#81]
In sclang one can plot ugens. It seems that this can be very useful for beginners like myself.
I understand that it can be tricky to implement though. Maybe there is a simpler way of getting intuition about values of various parts of the system? Thank you for the amazing project!

**Comment by ntrocado** [comment]
AFAIK plotting is not a feature of sclang per se, but more a feature of the IDE.
One way of using the scope, the frequency analyzer and other visualization tools in SuperCollider to analyze the audio signal is:
(a) open the SuperCollider IDE and run the following code:
``` SuperCollider
(
o = Server.local.options;
o = ServerOptions.new;
o.maxLogins = 2;
t = Server(\Local, NetAddr("127.0.0.1", 57110), o);
t.makeWindow;
t.boot;
FreqScope.new(server: t);
)
```
(b) on the LISP side, after loading the cl-collider library, start the server with:
``` lisp
(in-package #:sc-user)
(setf *s* (make-external-server "localhost" :port 57110 :just-connect-p t))
(server-boot *s*)
```
See [here](https://github.com/ntrocado/cl-collider-examples/blob/master/nick-collins-tutorial/2-1.lisp) for more examples.

You can also poll values. For example:
``` lisp
(play (poll.kr (impulse.kr 1) (white-noise.ar 220) "noise"))
```
You'll get the values printed every second at the REPL.

It should be relatively simple to implement a basic plotting facility for envelopes and buffers, using one of the available plotting libraries for Common Lisp. I've been thinking about doing it, but so far couldn't find the time…

More generally, if there's something more specific that you're having trouble debugging or making sense of, feel free to ask.

**Comment by ntrocado** [comment]
By the way, here's a quick way of plotting envelopes:

``` lisp
CL-USER> (ql:quickload '("kai" "cl-collider"))
To load "kai":
  Load 1 ASDF system:
    kai
; Loading "kai"

To load "cl-collider":
  Load 1 ASDF system:
    cl-collider
; Loading "cl-collider"
("kai" "cl-collider")

CL-USER> (in-package :sc-user)
#<PACKAGE "SC-USER">

SC-USER> (let ((envelope (env '(0 1 .2 .8 .1 0)
			      '(.01 .3 2.5 .3 2)
			      '(:lin :exp :exp :cub :lin))))
	   (kai:line (env-as-signal envelope 100)))
T
SC-USER> (kai:show)
T
```

This interactive plot will open on your browser:
![image](https://user-images.githubusercontent.com/10780358/108863624-4aefee80-75e9-11eb-9e6c-64479b2098cc.png)

**Comment by byulparan** [comment]
great!

**Comment by TatriX** [comment]
I wanted to plot ugens output and here's what I ended up doing:
```
(ql:quickload :vgplot)

(defun buffer-plot (buffer &key (bin-width 64) (sample-rate 48000))
  (vgplot:axis (list 0 (/ sample-rate bin-width)
                     -1 1))
  (vgplot:plot (loop for x in (buffer-get-to-list buffer)
                     for i from 0
                     when (zerop (mod i bin-width))
                       collect x)))

(defconstant +plot-dur+ 1)
(defvar *b* (buffer-alloc (* +plot-dur+ +sample-rate+)))

(buffer-fill *b* :sine (list 1 0.5 0.25))

(vgplot:subplot 2 2 0)
(buffer-plot *b*)

(proxy :plot
       (* 0 (buf-wr.ar (sin-osc.ar 4) *b* (line.ar 0 (buf-frames.kr *b*) +plot-dur+ :act :free))))

(vgplot:subplot 2 2 1)
(buffer-plot *b*)

(proxy :plot
       (* 0 (buf-wr.ar (lf-pulse.ar 3) *b* (line.ar 0 (buf-frames.kr *b*) +plot-dur+ :act :free))))

(vgplot:subplot 2 2 2)
(buffer-plot *b*)

(proxy :plot
       (* 0 (buf-wr.ar (- (lf-pulse.ar 3) (sin-osc.ar 1/3))
                       *b*
                       (line.ar 0 (buf-frames.kr *b*) +plot-dur+ :act :free))))

(vgplot:subplot 2 2 3)
(buffer-plot *b*)
```
![2021-05-23-145408_1314x1254_scrot](https://user-images.githubusercontent.com/703150/119261216-bc364200-bbd6-11eb-9b22-3d102364e003.png)

**Comment by defaultxr** [comment]
@TatriX, this is good, but instead of using `buffer-get-to-list` you're probably better using just `buffer-to-list` since that function will automatically use the fastest available method to acquire the frames from the buffer.

**Comment by defaultxr** [comment]
...Also keep in mind that the `buffer-to-list` functions will acquire all of the frames as they are ordered in the buffer itself, i.e. the channels are interlaced. So buffers with more than one channel may look incorrect. `buffer-to-array` separates each channel into its own sub-array so it might be more convenient to plot based on that one if you're going to be working with multi-channel buffers.
