### ISSUE TITLE
Suddenly no sound during playing, and (SERVER-STATUS *S*) gives no output.

### ISSUE THREAD

**Issue by BlueFlo0d** [byulparan/cl-collider#86]
As described, the system works fine for some time then abruptly fall to silence (with a hard-cut-to-zero audio glitch sound). I then try `(server-status *s*)`, `(server-query-all-nodes)`, all gives no output. (They were giving out put when it's normally making sound)

I know this might not be so informative, but is there anyway to get more detailed error messages? (like, from a log somewhere). The `scsynth` process is still running, just not making sound.

I'm on macOS 10.14, with SuperCollider 3.11.0 and Clozure CL 1.11.6

**Comment by BlueFlo0d** [comment]
I messed with it for a while, turns out that this also happens if I play nothing and just let the server idle for a while so this should not be a bug in my synths.

**Comment by byulparan** [comment]
Can you test on SBCL and SCLang? or shared your test code.

I don't know that's cl-collider problem or scsynth or sound card or clozure cl or your code.

**Comment by BlueFlo0d** [comment]
The minimal code to reproduce the issue is just
```
(setf *s*
      (make-external-server
       "localhost"
       :port 48800))
(server-boot *s*)
```
Then leave it for a while and it will crash. I tested with supercollider 3.10.4 with no luck.

Let me try SBCL.

**Comment by BlueFlo0d** [comment]
This also happens on SBCL after I leave it idle for 3 minutes. I'm on SBCL 1.5.1.

Seems hard to locate the issue, any idea? If there's something like a log file it'll be easier, I think.

**Comment by byulparan** [comment]
hmm.. it seems not cl-collider issue.
cl-collider is only send / receive message when execute code.
If you leave it idle after server boot,  cl-collider do nothing.

no output with `server-status` / `server-query-all-nodes` then that's server problem.
hmm..  is it ok on SuperCollider IDE(SCLang, SCSynth)?

I use MacOS 10.15.4 / ClozureCL 1.12-dev / SBCL 2.0.3 / SuperCollider 3.11.0.

**Comment by BlueFlo0d** [comment]
Ah, I see, so I might be in deep trouble.

I've never used SC IDE before, let me find some tutorial and try it.

**Comment by BlueFlo0d** [comment]
Seems that it works after I replaced my UAD drivers. So it's some sound card issue.

Closing it now. Sorry for bothering!
