### ISSUE TITLE
Is this client complete?

### ISSUE THREAD

**Issue by brandflake11** [byulparan/cl-collider#88]
Hello,
I badly want to program with supercollider, but want to do it with lisp. Is this client complete? Is it missing any big noticeable features to stop it from allowing supercollider to be used to its fullest?

Thank you very much for your time.

**Comment by defaultxr** [comment]
I've been using cl-collider to make music and noise for a while now and have even written a few libraries building upon it. I don't think there are any major features missing if you want to make sound with SuperCollider and Lisp. Obviously you won't be able to directly translate everything from SC into Lisp but most basic things should be possible.

The best way to answer your question is to just use cl-collider and find out. If you notice anything missing, feel free to open a specific issue about it.

**Comment by byulparan** [comment]
maybe GUI?(button, slider, plot...). but I think It's not cl-collider's range.

**Comment by brandflake11** [comment]
I see. The reason I ask, is I don't like supercollider's syntax, but lisp is great. If I can use the features of supercollider using lisp with this, that would be a dream.
