### ISSUE TITLE
local-buf not working ?

### ISSUE THREAD

**Issue by vrx** [byulparan/cl-collider#9]
(local-buf 2048)
sends : 

There is no applicable method for the generic function:
  #<STANDARD-GENERIC-FUNCTION SC::MAX-LOCAL-BUFS #x30200156DAFF>
when called with arguments:
  (NIL)

**Comment by byulparan** [comment]
'local-buf' should be call in synth definition form(defsynth, proxy).
It same to SuperCollider. 
in SuperCollider, call 'LocalBuf(2048)'  then signal error 
"ERROR: Message 'maxLocalBufs' not understood."
